config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"
  
  
  get '/' => 'static_pages#home', as: :root
  get '/home' => 'static_pages#home', as: :home
  
  get '/help' => 'static_pages#help', as: :help
  get '/about' => 'static_pages#about', as: :about
  get '/contact' => 'static_pages#contact', as: :contact
  
  get '/signup' => 'users#new', as: :signup

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
  def decideTitle(title)
    baseName = 'RoR Sample App'
    if title.empty?
      baseName
    else
      "#{baseName} | #{title}"
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small><%= link_to "&copy; Abhijeet".html_safe, "http://abhijeet.pro/", target: "__blank" %></small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Rails news", "http://news.railstutorial.org/", target: "__blank" %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Sample app", home_path, id: 'logo' %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", home_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", "#" %></li>
				</ul>
			</nav>
		</div>
		
	</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= decideTitle(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
	
	<%= render "layouts/header" %>
	
	<div class="container">
		<%= yield %>
		
		<%= render "layouts/footer" %>
	</div>
	

</body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About') %>
<div class="center hero-unit">
	<h1>Sample App | About</h1>
	<p>
		This is the home page for the
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</p>
</div>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<div class="center hero-unit">
	<h1>Contact Me</h1>
	<p>
		This is the contact page for the
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</p>
	<p><%= link_to "Sign up now!", "#", class: "btn btn-large btn-primary" %></p>
</div>
<p><%= link_to image_tag("ror.jpeg", alt: "Ruby on rails", height: 100, width: 100) %></p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>
<div class="center hero-unit">
	<h1>Help</h1>
	<p>
		Get help on the Ruby on Rails Tutorial at the
		<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
		To get help on this sample app, see the
		<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
	</p>
</div>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home') %>
<div class="center hero-unit">
	<h1>Welcome to Sample App</h1>
	<p>
		This is the home page for the
		<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</p>
	<p><%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %></p>
</div>
<p><%= link_to image_tag("ror.jpeg", alt: "Ruby on rails", height: 100, width: 100) %></p>

app/views/users/new.html.erb
<%= provide(:title, 'Signup') %>

<div class="center hero-unit">
	<h1>Signup</h1>
	<p>Find me in app/views/users/new.html.erb</p>
</div>